input: {
        train_file: "input/train.csv",
        test_file: "",
        validation_file: "",
        output_path: "output"
        }
cross_validation: {
                target_cols: ["target"],
                problem_type: "multilabel_classification",
                multilabel_delimiter: " ",
                shuffle: True,
                num_folds: 5,
                random_state: 42
                }
catergorical_features: {

                        }
numerical_features: {

                    }