input: {
        train_file: "input/train.csv",
        test_file: "input/test.csv",
        target_cols: ["target"],
        output_path: "output"
        }
feature_selection: {
        categorical_features: {
                        enc_types: "label",
                        handle_na: True,
                        num_best: 5,
                        },
        numerical_features: {

                    },
        cols_to_drop: ['id']

}
cross_validation: {
                problem_type: "binary_classification",
                multilabel_delimiter: " ",
                shuffle: True,
                num_folds: 5,
                random_state: 42
                }
training: {
        model: "logistic"
}
diagnosis: {
        goodness_of_fit: {

        },
        statistical_significance: {

        }
}