input: {
        train_file: "input/train.csv",
        test_file: "input/test.csv",
        target_cols: ["target"],
        output_path: "output"
        }
categorical_features: {
                        enc_type: "label",
                        handle_na: True
                        }
numerical_features: {

                    }
cross_validation: {
                problem_type: "binary_classification",
                multilabel_delimiter: " ",
                shuffle: True,
                num_folds: 5,
                random_state: 42
                }
training: {
        model: "logistic"
}