input: {
        train_file: "input/home-data-for-ml-course/train.csv",
        test_file: "input/home-data-for-ml-course/test.csv",
        target_cols: ["SalePrice"],
        output_path: "output"
        }
cross_validation: {
                target_cols: ["SalePrice"],
                problem_type: "single_column_regression",
                multilabel_delimiter: " ",
                shuffle: True,
                num_folds: 5,
                random_state: 42
                }
categorical_features: {
                        enc_type: "label",
                        handle_na: True
                        }
numerical_features: {

                    }