input: {
        train_file: "input/train.csv",
        test_file: "",
        output_path: "output"
        }
cross_validation: {
                target_cols: ["target"],
                problem_type: "multilabel_classification",
                multilabel_delimiter: " ",
                shuffle: True,
                num_folds: 5,
                random_state: 42
                }
catergorical_features: {
                        # the vlaue of this key will be filled by the pipeline automatically 
                        categorical_features: [],
                        enc_type: "ohe",
                        handle_na: False
                        }
numerical_features: {

                    }